# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WAMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('category_id', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DealsHubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.TextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dealshub.Category')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Product')),
            ],
            options={
                'verbose_name': 'DealsHub Product',
                'verbose_name_plural': 'DealsHub Products',
            },
        ),
        migrations.CreateModel(
            name='PossibleValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('lable', models.CharField(blank=True, default='', max_length=256)),
                ('value', models.CharField(blank=True, default='', max_length=256)),
                ('unit', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Possible Value',
                'verbose_name_plural': 'Possible Values',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('desription', models.CharField(blank=True, default='', max_length=256)),
                ('sub_category_id', models.CharField(blank=True, default='', max_length=256)),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='dealshub.Category')),
            ],
            options={
                'verbose_name': 'Sub-category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='subcategory',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='dealshub.SubCategory'),
        ),
        migrations.AddField(
            model_name='possiblevalues',
            name='prop',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dealshub.Property'),
        ),
        migrations.AddField(
            model_name='dealshubproduct',
            name='sub_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dealshub.SubCategory'),
        ),
    ]
