# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-13 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WAMSApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('category_id', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryGridBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('http_link', models.TextField(default='')),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='DealsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('http_link', models.TextField(default='')),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='DealsHubHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Brand')),
                ('categories', models.ManyToManyField(blank=True, to='dealshub.Category')),
            ],
        ),
        migrations.CreateModel(
            name='DealsHubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.TextField(blank=True, default='{}', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealshub.Category')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Product')),
            ],
            options={
                'verbose_name': 'DealsHub Product',
                'verbose_name_plural': 'DealsHub Products',
            },
        ),
        migrations.CreateModel(
            name='FullBannerAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('http_link', models.TextField(default='')),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSchedular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('http_link', models.TextField(default='')),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('http_link', models.TextField(default='')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('value', models.CharField(blank=True, default='', max_length=256)),
                ('unit', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Possible Value',
                'verbose_name_plural': 'Possible Values',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('listing_type', models.CharField(default='Carousel', max_length=200)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='WAMSApp.Product')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('desription', models.CharField(blank=True, default='', max_length=256)),
                ('sub_category_id', models.CharField(blank=True, default='', max_length=256)),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='dealshub.Category')),
            ],
            options={
                'verbose_name': 'Sub-category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='subcategory',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='dealshub.SubCategory'),
        ),
        migrations.AddField(
            model_name='possiblevalues',
            name='prop',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dealshub.Property'),
        ),
        migrations.AddField(
            model_name='dealshubproduct',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealshub.SubCategory'),
        ),
        migrations.AddField(
            model_name='dealshubheading',
            name='image_links',
            field=models.ManyToManyField(blank=True, to='dealshub.ImageLink'),
        ),
    ]
