# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealshub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealshubproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealshub.Category'),
        ),
        migrations.AlterField(
            model_name='dealshubproduct',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealshub.SubCategory'),
        ),
    ]
