# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealshub', '0002_auto_20200128_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possiblevalues',
            name='lable',
        ),
        migrations.AddField(
            model_name='possiblevalues',
            name='label',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
