# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealshub', '0003_auto_20200204_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealshubproduct',
            name='properties',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
