# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WAMSApp', '0004_auto_20200204_1545'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealshub', '0004_auto_20200204_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('listing_type', models.CharField(default='Carousel', max_length=200)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='WAMSApp.Product')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
