# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-03 12:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Background Image',
                'verbose_name_plural': 'Background Images',
            },
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField()),
                ('seller_sku', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(default=b'', max_length=200)),
                ('subtitle', models.CharField(default=b'', max_length=200)),
                ('manufacturer', models.CharField(default=b'', max_length=200)),
                ('manufacturer_part_number', models.CharField(default=b'', max_length=200)),
                ('package_length', models.FloatField(blank=True, null=True)),
                ('package_length_metric', models.CharField(default=b'', max_length=100)),
                ('package_width', models.FloatField(blank=True, null=True)),
                ('package_width_metric', models.CharField(default=b'', max_length=100)),
                ('package_height', models.FloatField(blank=True, null=True)),
                ('package_height_metric', models.CharField(default=b'', max_length=100)),
                ('package_weight', models.FloatField(blank=True, null=True)),
                ('package_weight_metric', models.CharField(default=b'', max_length=100)),
                ('package_quantity', models.CharField(default=b'', max_length=100)),
                ('shipping_weight', models.FloatField(blank=True, null=True)),
                ('shipping_weight_metric', models.CharField(default=b'', max_length=100)),
                ('item_display_weight', models.FloatField(blank=True, null=True)),
                ('item_display_weight_metric', models.CharField(default=b'', max_length=100)),
                ('item_display_volume', models.FloatField(blank=True, null=True)),
                ('item_display_volume_metric', models.CharField(default=b'', max_length=100)),
                ('item_display_length', models.FloatField(blank=True, null=True)),
                ('item_display_length_metric', models.CharField(default=b'', max_length=100)),
                ('item_weight', models.FloatField(blank=True, null=True)),
                ('item_weight_metric', models.CharField(default=b'', max_length=100)),
                ('item_length', models.FloatField(blank=True, null=True)),
                ('item_length_metric', models.CharField(default=b'', max_length=100)),
                ('item_width', models.FloatField(blank=True, null=True)),
                ('item_width_metric', models.CharField(default=b'', max_length=100)),
                ('item_height', models.FloatField(blank=True, null=True)),
                ('item_height_metric', models.CharField(default=b'', max_length=100)),
                ('item_display_width', models.FloatField(blank=True, null=True)),
                ('item_display_width_metric', models.CharField(default=b'', max_length=100)),
                ('item_display_height', models.FloatField(blank=True, null=True)),
                ('item_display_height_metric', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name': 'BaseProduct',
                'verbose_name_plural': 'BaseProducts',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='ChannelProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noon_product_json', models.TextField(blank=True, default=b'{"msrp_ae_unit": "", "msrp_ae": "", "product_type": "", "product_attribute_list": [], "product_description": "", "created_date": "", "product_subtype": "", "model_name": "", "product_name": "", "model_number": ""}')),
                ('amazon_uk_product_json', models.TextField(blank=True, default=b'{"item_condition_note": "", "subtitle": "", "update_delete": "", "search_terms": "", "product_id_type": "", "feed_product_type": "", "item_count_metric": "", "recommended_browse_nodes": "", "enclosure_material": "", "sale_price": "", "relationship_type": "", "cover_material_type": "", "parent_sku": "", "sale_from": "", "parentage": "", "variation_theme": "", "product_attribute_list": [], "wattage": "", "product_description": "", "item_count": "", "sale_end": "", "condition_type": "", "created_date": "", "special_features": [], "number_of_items": "", "max_order_quantity": "", "product_name": "", "wattage_metric": ""}')),
                ('amazon_uae_product_json', models.TextField(blank=True, default=b'{"product_attribute_list": [], "update_delete": "", "product_description": "", "feed_product_type": "", "created_date": "", "recommended_browse_nodes": "", "product_name": ""}')),
                ('ebay_product_json', models.TextField(blank=True, default=b'{"category": "", "product_attribute_list": [], "created_date": "", "product_name": "", "product_description": ""}')),
            ],
            options={
                'verbose_name': 'ChannelProduct',
                'verbose_name_plural': 'ChannelProducts',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
            },
        ),
        migrations.CreateModel(
            name='ContentExecutive',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContentExecutive',
                'verbose_name_plural': 'ContentExecutives',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContentManager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContentManager',
                'verbose_name_plural': 'ContentManagers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.ManyToManyField(blank=True, to='WAMSApp.Brand')),
                ('channels', models.ManyToManyField(blank=True, to='WAMSApp.Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CustomPermission',
                'verbose_name_plural': 'CustomPermissions',
            },
        ),
        migrations.CreateModel(
            name='EbayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(default=b'', max_length=100)),
                ('name', models.CharField(default=b'', max_length=200)),
            ],
            options={
                'verbose_name': 'EbayCategory',
                'verbose_name_plural': 'EbayCategory',
            },
        ),
        migrations.CreateModel(
            name='ExportList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'SampleExportList', max_length=200)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ExportList',
                'verbose_name_plural': 'ExportLists',
            },
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'SampleFlyer', max_length=200)),
                ('template_data', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(default=b'A4 Portrait', max_length=100)),
            ],
            options={
                'verbose_name': 'Flyer',
                'verbose_name_plural': 'Flyers',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=b'')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=b'thumbnails')),
                ('mid_image', models.ImageField(blank=True, null=True, upload_to=b'midsize')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ImageBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_main_image', models.BooleanField(default=False)),
                ('is_sub_image', models.BooleanField(default=False)),
                ('sub_image_index', models.IntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Image')),
            ],
            options={
                'verbose_name': 'Image Bucket',
                'verbose_name_plural': 'Image Buckets',
            },
        ),
        migrations.CreateModel(
            name='MainImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sourced', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Channel')),
                ('main_images', models.ManyToManyField(blank=True, related_name='main_images', to='WAMSApp.ImageBucket')),
            ],
            options={
                'verbose_name': 'MainImages',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'MaterialType',
                'verbose_name_plural': 'MaterialTypes',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='PFL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'SamplePFL', max_length=200)),
                ('template_data', models.TextField(blank=True, null=True)),
                ('external_images_bucket', models.ManyToManyField(blank=True, to='WAMSApp.Image')),
            ],
            options={
                'verbose_name': 'PFL',
                'verbose_name_plural': 'PFL',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_id', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('status', models.CharField(default=b'Pending', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('uuid', models.CharField(max_length=200, null=True)),
                ('pfl_product_name', models.CharField(default=b'', max_length=250)),
                ('pfl_product_features', models.TextField(default=b'[]')),
                ('product_name_sap', models.CharField(default=b'', max_length=200)),
                ('color_map', models.CharField(default=b'', max_length=100)),
                ('color', models.CharField(default=b'', max_length=100)),
                ('standard_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('barcode_string', models.CharField(default=b'', max_length=100)),
                ('outdoor_price', models.FloatField(blank=True, null=True)),
                ('factory_notes', models.TextField(blank=True, null=True)),
                ('ads_images', models.ManyToManyField(blank=True, related_name='ads_images', to='WAMSApp.Image')),
                ('aplus_content_images', models.ManyToManyField(blank=True, related_name='aplus_content_images', to='WAMSApp.Image')),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Image')),
                ('base_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.BaseProduct')),
                ('certificate_images', models.ManyToManyField(blank=True, related_name='certificate_images', to='WAMSApp.Image')),
                ('channel_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.ChannelProduct')),
                ('diecut_images', models.ManyToManyField(blank=True, related_name='diecut_images', to='WAMSApp.Image')),
                ('giftbox_images', models.ManyToManyField(blank=True, related_name='giftbox_images', to='WAMSApp.Image')),
                ('lifestyle_images', models.ManyToManyField(blank=True, related_name='lifestyle_images', to='WAMSApp.Image')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.MaterialType')),
                ('pfl_generated_images', models.ManyToManyField(blank=True, related_name='pfl_generated_images', to='WAMSApp.Image')),
                ('pfl_images', models.ManyToManyField(blank=True, related_name='pfl_images', to='WAMSApp.Image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductIDType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'ProductIDType',
                'verbose_name_plural': 'ProductIDTypes',
            },
        ),
        migrations.CreateModel(
            name='SubImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sourced', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Channel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='WAMSApp.Product')),
                ('sub_images', models.ManyToManyField(blank=True, related_name='sub_images', to='WAMSApp.ImageBucket')),
            ],
            options={
                'verbose_name': 'SubImages',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.ProductIDType'),
        ),
        migrations.AddField(
            model_name='product',
            name='transparent_images',
            field=models.ManyToManyField(blank=True, related_name='transparent_images', to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='unedited_images',
            field=models.ManyToManyField(blank=True, related_name='unedited_images', to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='white_background_images',
            field=models.ManyToManyField(blank=True, related_name='white_background_images', to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='pfl',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Product'),
        ),
        migrations.AddField(
            model_name='pfl',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='mainimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Product'),
        ),
        migrations.AddField(
            model_name='flyer',
            name='background_images_bucket',
            field=models.ManyToManyField(blank=True, related_name='background_images_bucket', to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='flyer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Brand'),
        ),
        migrations.AddField(
            model_name='flyer',
            name='external_images_bucket',
            field=models.ManyToManyField(blank=True, to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='flyer',
            name='flyer_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flyer_images', to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='flyer',
            name='product_bucket',
            field=models.ManyToManyField(blank=True, to='WAMSApp.Product'),
        ),
        migrations.AddField(
            model_name='exportlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='WAMSApp.Product'),
        ),
        migrations.AddField(
            model_name='exportlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='config',
            name='product_404_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Organization'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WAMSApp.Brand'),
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Image'),
        ),
    ]
