# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-17 07:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WAMSApp', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('body', models.CharField(max_length=200)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=100)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WAMSApp.Image')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='SalesAppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fcm_id', models.TextField(default='')),
                ('contact_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('favourite_products', models.ManyToManyField(blank=True, to='WAMSApp.Product')),
            ],
            options={
                'verbose_name': 'SalesAppUser',
                'verbose_name_plural': 'SalesAppUsers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
