[
    {"variable": "product_name", "name": "Product Name"},
    {"variable": "product_id", "name": "Product ID"},
    {"variable": "product_id_type", "name": "Product ID Type"},
    {"variable": "product_description", "name": "Product Description"},
    {"variable": "pfl_product_feature_1", "name": "Product Feature 1"},
    {"variable": "pfl_product_feature_2", "name": "Product Feature 2"},
    {"variable": "pfl_product_feature_3", "name": "Product Feature 3"},
    {"variable": "pfl_product_feature_4", "name": "Product Feature 4"},
    {"variable": "pfl_product_feature_5", "name": "Product Feature 5"},
    {"variable": "color_map", "name": "Color Map"},
    {"variable": "color", "name": "Color"},
    {"variable": "material_type", "name": "Material Type"},
    {"variable": "standard_price", "name": "Standard Price"},
    {"variable": "currency", "name": "Currency"},
    {"variable": "quantity", "name": "Quantity"},
    {"variable": "main_image", "name": "Main Image"},
    {"variable": "sub_image_1", "name": "Sub Image 1"},
    {"variable": "sub_image_2", "name": "Sub Image 2"},
    {"variable": "sub_image_3", "name": "Sub Image 3"},
    {"variable": "sub_image_4", "name": "Sub Image 4"},
    {"variable": "sub_image_5", "name": "Sub Image 5"},
    {"variable": "white_background_image_1", "name": "White Background Image 1"},
    {"variable": "white_background_image_2", "name": "White Background Image 2"},
    {"variable": "white_background_image_3", "name": "White Background Image 3"},
    {"variable": "white_background_image_4", "name": "White Background Image 4"},
    {"variable": "white_background_image_5", "name": "White Background Image 5"},
    {"variable": "lifestyle_image_1", "name": "Lifestyle Image 1"},
    {"variable": "lifestyle_image_2", "name": "Lifestyle Image 2"},
    {"variable": "lifestyle_image_3", "name": "Lifestyle Image 3"},
    {"variable": "lifestyle_image_4", "name": "Lifestyle Image 4"},
    {"variable": "lifestyle_image_5", "name": "Lifestyle Image 5"},
    {"variable": "certificate_image_1", "name": "Certificate Image 1"},
    {"variable": "certificate_image_2", "name": "Certificate Image 2"},
    {"variable": "certificate_image_3", "name": "Certificate Image 3"},
    {"variable": "certificate_image_4", "name": "Certificate Image 4"},
    {"variable": "certificate_image_5", "name": "Certificate Image 5"},
    {"variable": "giftbox_image_1", "name": "Giftbox Image 1"},
    {"variable": "giftbox_image_2", "name": "Giftbox Image 2"},
    {"variable": "giftbox_image_3", "name": "Giftbox Image 3"},
    {"variable": "giftbox_image_4", "name": "Giftbox Image 4"},
    {"variable": "giftbox_image_5", "name": "Giftbox Image 5"},
    {"variable": "diecut_image_1", "name": "Diecut Image 1"},
    {"variable": "diecut_image_2", "name": "Diecut Image 2"},
    {"variable": "diecut_image_3", "name": "Diecut Image 3"},
    {"variable": "diecut_image_4", "name": "Diecut Image 4"},
    {"variable": "diecut_image_5", "name": "Diecut Image 5"},
    {"variable": "aplus_content_image_1", "name": "A+ Content Image 1"},
    {"variable": "aplus_content_image_2", "name": "A+ Content Image 2"},
    {"variable": "aplus_content_image_3", "name": "A+ Content Image 3"},
    {"variable": "aplus_content_image_4", "name": "A+ Content Image 4"},
    {"variable": "aplus_content_image_5", "name": "A+ Content Image 5"},
    {"variable": "ads_image_1", "name": "Ads Image 1"},
    {"variable": "ads_image_2", "name": "Ads Image 2"},
    {"variable": "ads_image_3", "name": "Ads Image 3"},
    {"variable": "ads_image_4", "name": "Ads Image 4"},
    {"variable": "ads_image_5", "name": "Ads Image 5"},
    {"variable": "transparent_image_1", "name": "Transparent Image 1"},
    {"variable": "transparent_image_2", "name": "Transparent Image 2"},
    {"variable": "transparent_image_3", "name": "Transparent Image 3"},
    {"variable": "transparent_image_4", "name": "Transparent Image 4"},
    {"variable": "transparent_image_5", "name": "Transparent Image 5"},
    {"variable": "unedited_image_1", "name": "Unedited Image 1"},
    {"variable": "unedited_image_2", "name": "Unedited Image 2"},
    {"variable": "unedited_image_3", "name": "Unedited Image 3"},
    {"variable": "unedited_image_4", "name": "Unedited Image 4"},
    {"variable": "unedited_image_5", "name": "Unedited Image 5"},
    {"variable": "barcode_string", "name": "Barcode"},
    {"variable": "factory_notes", "name": "Factory Notes"},
    {"variable": "seller_sku", "name": "Seller SKU"},
    {"variable": "category", "name": "Category"},
    {"variable": "sub_category", "name": "SubCategory"},
    {"variable": "brand", "name": "Brand"},
    {"variable": "manufacturer", "name": "Manufacturer"},
    {"variable": "manufacturer_part_number", "name": "Manufacturer Part Number"},
    {"variable": "export_carton_quantity_l", "name": "Export Carton Quantity Length"},
    {"variable": "export_carton_quantity_l_metric", "name": "Export Carton Quantity Length Metric"},
    {"variable": "export_carton_quantity_b", "name": "Export Carton Quantity Breadth"},
    {"variable": "export_carton_quantity_b_metric", "name": "Export Carton Quantity Breadth Metric"},
    {"variable": "export_carton_quantity_h", "name": "Export Carton Quantity Height"},
    {"variable": "export_carton_quantity_h_metric", "name": "Export Carton Quantity Height Metric"},
    {"variable": "export_carton_crm_l", "name": "Export Carton CBM Length"},
    {"variable": "export_carton_crm_l_metric", "name": "Export Carton CBM Length Metric"},
    {"variable": "export_carton_crm_b", "name": "Export Carton CBM Breadth"},
    {"variable": "export_carton_crm_b_metric", "name": "Export Carton CBM Breadth Metric"},
    {"variable": "export_carton_crm_h", "name": "Export Carton CBM Height Metric"},
    {"variable": "export_carton_crm_h_metric", "name": "Export Carton CBM Height Metric"},
    {"variable": "product_dimension_l", "name": "Product Dimension Length"},
    {"variable": "product_dimension_l_metric", "name": "Product Dimension Length Metric"},
    {"variable": "product_dimension_b", "name": "Product Dimension Breadth"},
    {"variable": "product_dimension_b_metric", "name": "Product Dimension Breadth Metric"},
    {"variable": "product_dimension_h", "name": "Product Dimension Height"},
    {"variable": "product_dimension_h_metric", "name": "Product Dimension Height Metric"},
    {"variable": "giftbox_l", "name": "Giftbox Length"},
    {"variable": "giftbox_l_metric", "name": "Giftbox Length Metric"},
    {"variable": "giftbox_b", "name": "Giftbox Length Breadth"},
    {"variable": "giftbox_b_metric", "name": "Giftbox Length Metric"},
    {"variable": "giftbox_h", "name": "Giftbox Length Height"},
    {"variable": "giftbox_h_metric", "name": "Giftbox Height Metric"},
    {"variable": "amazonuk_product_name", "name": "Amazon UK Product Name"},
    {"variable": "amazonuk_product_description", "name": "Amazon UK Product Description"},
    {"variable": "amazonuk_product_attribute_list_1", "name": "Amazon UK Product Attribute List 1"},
    {"variable": "amazonuk_product_attribute_list_2", "name": "Amazon UK Product Attribute List 2"},
    {"variable": "amazonuk_product_attribute_list_3", "name": "Amazon UK Product Attribute List 3"},
    {"variable": "amazonuk_product_attribute_list_4", "name": "Amazon UK Product Attribute List 4"},
    {"variable": "amazonuk_product_attribute_list_5", "name": "Amazon UK Product Attribute List 5"},
    {"variable": "amazonuk_category", "name": "Amazon UK Category"},
    {"variable": "amazonuk_sub_category", "name": "Amazon UK SubCategory"},
    {"variable": "amazonuk_parentage", "name": "Amazon UK Parentage"},
    {"variable": "amazonuk_parent_sku", "name": "Amazon UK Parent SKU"},
    {"variable": "amazonuk_relationship_type", "name": "Amazon UK Relationship Type"},
    {"variable": "amazonuk_variation_theme", "name": "Amazon UK Variation Theme"},
    {"variable": "amazonuk_feed_product_type", "name": "Amazon UK Feed Product Type"},
    {"variable": "amazonuk_update_delete", "name": "Amazon UK Update Delete"},
    {"variable": "amazonuk_recommended_browse_nodes", "name": "Amazon UK Recommended Browse Nodes"},
    {"variable": "amazonuk_search_terms", "name": "Amazon UK Search Terms"},
    {"variable": "amazonuk_enclosure_material", "name": "Amazon UK Enclosure Material"},
    {"variable": "amazonuk_cover_material_type", "name": "Amazon UK Cover Material Type"},
    {"variable": "amazonuk_special_feature_1", "name": "Amazon UK Special Feature 1"},
    {"variable": "amazonuk_special_feature_2", "name": "Amazon UK Special Feature 2"},
    {"variable": "amazonuk_special_feature_3", "name": "Amazon UK Special Feature 3"},
    {"variable": "amazonuk_special_feature_4", "name": "Amazon UK Special Feature 4"},
    {"variable": "amazonuk_special_feature_5", "name": "Amazon UK Special Feature 5"},
    {"variable": "amazonuk_sale_price", "name": "Amazon UK Sale Price"},
    {"variable": "amazonuk_sale_from", "name": "Amazon UK Sale From"},
    {"variable": "amazonuk_sale_end", "name": "Amazon UK Sale End"},
    {"variable": "amazonuk_wattage", "name": "Amazon UK Wattage"},
    {"variable": "amazonuk_wattage_metric", "name": "Amazon UK Wattage Metric"},
    {"variable": "amazonuk_item_count", "name": "Amazon UK Item Count"},
    {"variable": "amazonuk_item_count_metric", "name": "Amazon UK Item Count Metric"},
    {"variable": "amazonuk_item_condition_note", "name": "Amazon UK Item Condition Note"},
    {"variable": "amazonuk_max_order_quantity", "name": "Amazon UK Max Order Quantity"},
    {"variable": "amazonuk_number_of_items", "name": "Amazon UK Number of Items"},
    {"variable": "amazonuk_condition_type", "name": "Amazon UK Condition Type"},
    {"variable": "amazonuk_package_length", "name": "Amazon UK Package Length"},
    {"variable": "amazonuk_package_length_metric", "name": "Amazon UK Package Length Metric"},
    {"variable": "amazonuk_package_width", "name": "Amazon UK Package Width"},
    {"variable": "amazonuk_package_width_metric", "name": "Amazon UK Package Width Metric"},
    {"variable": "amazonuk_package_height", "name": "Amazon UK Package Height"},
    {"variable": "amazonuk_package_height_metric", "name": "Amazon UK Package Height Metric"},
    {"variable": "amazonuk_package_weight", "name": "Amazon UK Package Weight"},
    {"variable": "amazonuk_package_weight_metric", "name": "Amazon UK Package Weight Metric"},
    {"variable": "amazonuk_package_quantity", "name": "Amazon UK Package Quantity"},
    {"variable": "amazonuk_shipping_weight", "name": "Amazon UK Shipping Weight"},
    {"variable": "amazonuk_shipping_weight_metric", "name": "Amazon UK Shipping Weight Metric"},
    {"variable": "amazonuk_item_display_weight", "name": "Item Display Weight"},
    {"variable": "amazonuk_item_display_weight_metric", "name": "Amazon UK Item Display Weight Metric"},
    {"variable": "amazonuk_item_display_volume", "name": "Amazon UK Item Display Volume"},
    {"variable": "amazonuk_item_display_volume_metric", "name": "Amazon UK Item Display Volume Metric"},
    {"variable": "amazonuk_item_display_length", "name": "Amazon UK Item Display Length"},
    {"variable": "amazonuk_item_display_length_metric", "name": "Amazon UK Item Display Length Metric"},
    {"variable": "amazonuk_item_weight", "name": "Amazon UK Item Weight"},
    {"variable": "amazonuk_item_weight_metric", "name": "Amazon UK Item Weight Metric"},
    {"variable": "amazonuk_item_length", "name": "Amazon UK Item Length"},
    {"variable": "amazonuk_item_length_metric", "name": "Amazon UK Item Length Metric"},
    {"variable": "amazonuk_item_width", "name": "Amazon UK Item Width"},
    {"variable": "amazonuk_item_width_metric", "name": "Amazon UK Item Width Metric"},
    {"variable": "amazonuk_item_height", "name": "Amazon UK Item Height"},
    {"variable": "amazonuk_item_heigth_metric", "name": "Amazon UK Item Height Metric"},
    {"variable": "amazonuk_item_display_width", "name": "Amazon UK Item Display Width"},
    {"variable": "amazonuk_item_display_width_metric", "name": "Amazon UK Item Display Width Metric"},
    {"variable": "amazonuk_item_display_height", "name": "Amazon UK Item Display Height"},
    {"variable": "amazonuk_item_display_height_metric", "name": "Amazon UK Item Display Height Metric"},
    {"variable": "amazonuk_http_link", "name": "Amazon UK HTTP Link"},

    {"variable": "amazonuae_product_name", "name": "Amazon UAE Product Name"},
    {"variable": "amazonuae_product_description", "name": "Amazon UAE Product Description"},
    {"variable": "amazonuae_product_attribute_list_1", "name": "Amazon UAE Product Attribute 1"},
    {"variable": "amazonuae_product_attribute_list_2", "name": "Amazon UAE Product Attribute 2"},
    {"variable": "amazonuae_product_attribute_list_3", "name": "Amazon UAE Product Attribute 3"},
    {"variable": "amazonuae_product_attribute_list_4", "name": "Amazon UAE Product Attribute 4"},
    {"variable": "amazonuae_product_attribute_list_5", "name": "Amazon UAE Product Attribute 5"},
    {"variable": "amazonuae_category", "name": "Amazon UAE Category"},
    {"variable": "amazonuae_sub_category", "name": "Amazon UAE SubCategory"},
    {"variable": "amazonuae_feed_product_type", "name": "Amazon UAE Feed Product Type"},
    {"variable": "amazonuae_recommended_browse_nodes", "name": "Amazon UAE Recommended Browse Nodes"},
    {"variable": "amazonuae_update_delete", "name": "Amazon UAE Update Delete"},
    {"variable": "amazonuae_http_link", "name": "Amazon UAE HTTP Link"},

    {"variable": "ebay_category", "name": "Ebay Category"},
    {"variable": "ebay_sub_category", "name": "Ebay SubCategory"},
    {"variable": "ebay_product_name", "name": "Ebay Product Name"},
    {"variable": "ebay_product_description", "name": "Ebay Product Description"},
    {"variable": "ebay_product_attribute_list_1", "name": "Ebay Product Attribute 1"},
    {"variable": "ebay_product_attribute_list_2", "name": "Ebay Product Attribute 2"},
    {"variable": "ebay_product_attribute_list_3", "name": "Ebay Product Attribute 3"},
    {"variable": "ebay_product_attribute_list_4", "name": "Ebay Product Attribute 4"},
    {"variable": "ebay_product_attribute_list_5", "name": "Ebay Product Attribute 5"},
    {"variable": "ebay_http_link", "name": "Ebay HTTP Link"},

    {"variable": "noon_product_name", "name": "Noon Product Name"},
    {"variable": "noon_product_type", "name": "Noon Product Type"},
    {"variable": "noon_product_subtype", "name": "Noon Product SubType"},
    {"variable": "noon_parent_sku", "name": "Noon Parent SKU"},
    {"variable": "noon_category", "name": "Noon Category"},
    {"variable": "noon_subtitle", "name": "Noon SubTitle"},
    {"variable": "noon_sub_category", "name": "Noon SubCategory"},
    {"variable": "noon_model_number", "name": "Noon Model Number"},
    {"variable": "noon_model_name", "name": "Noon Noon Model Name"},
    {"variable": "noon_msrp_ae", "name": "Noon MSRP AE"},
    {"variable": "noon_msrp_ae_unit", "name": "Noon MSRP AE Unit"},
    {"variable": "noon_product_description", "name": "Noon Product Description"},
    {"variable": "product_attribute_list_1", "name": "Noon Attribute 1"},
    {"variable": "product_attribute_list_2", "name": "Noon Attribute 2"},
    {"variable": "product_attribute_list_3", "name": "Noon Attribute 3"},
    {"variable": "product_attribute_list_4", "name": "Noon Attribute 4"},
    {"variable": "product_attribute_list_5", "name": "Noon Attribute 5"},
    {"variable": "noon_http_link", "name": "Noon HTTP Link"}
]